# Site settings
title: Griffin Moe
email: me@griffin.moe
tagline: > # duped for SEO
  I'm a software engineer experimenting in the intersection of computers and
  music on the web and in your DAW.
description: >
  I'm a software engineer experimenting in the intersection of computers and
  music on the web and in your DAW.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://griffin.moe" # the base hostname & protocol for your site
permalink: /posts/:year/:month/:day/:title

# SEO stuff
author: griffin_moe
twitter:
  username: griffin_moe
  card: summary
github_username: gmoe # using above struct breaks gh-pages
social:
  name: Griffin Moe
  links:
    - https://twitter.com/griffin_moe
    - https://github.com/gmoe

# Build settings
markdown: kramdown
exclude: ["CNAME", "README.md"]
