# Site settings
title: Griffin Moe
email: me@griffinmoe.com
description: >
  I'm a software engineer experimenting in the intersection of computers and
  music on the web and in your DAW.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://griffinmoe.com" # the base hostname & protocol for your site
twitter_username: griffin_moe
github_username:  gmoe

# Build settings
markdown: kramdown
exclude: ["CNAME", "README.md"]
